//AUTOGENERATED FILE FROM png2asset
// Conversion args: /title_bg.png -o /title_bg.c -map -use_map_attributes -b 7 -max_palettes 8

#ifndef METASPRITE_title_bg_H
#define METASPRITE_title_bg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define title_bg_TILE_ORIGIN 0
#define title_bg_TILE_W 8
#define title_bg_TILE_H 8
#define title_bg_WIDTH 160
#define title_bg_HEIGHT 144
#define title_bg_TILE_COUNT 188
#define title_bg_PALETTE_COUNT 8
#define title_bg_COLORS_PER_PALETTE 4
#define title_bg_TOTAL_COLORS 32
#define title_bg_MAP_ATTRIBUTES title_bg_map_attributes
#define title_bg_MAP_ATTRIBUTES_WIDTH 20
#define title_bg_MAP_ATTRIBUTES_HEIGHT 18
#define title_bg_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define title_bg_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char title_bg_map[360];
extern const unsigned char title_bg_map_attributes[360];

BANKREF_EXTERN(title_bg)

extern const palette_color_t title_bg_palettes[32];
extern const uint8_t title_bg_tiles[3008];

#endif
